name: CI
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo Test!
  create:
    runs-on: ubuntu-latest
    needs: test
    if: github.event.created
    steps:
      - uses: actions/checkout@v3
      - run: echo Created!
  build:
    runs-on: ubuntu-latest
    needs: create
    if: always() && (needs.create.result == 'skipped' || needs.create.result == 'success')
    steps:
      - uses: actions/checkout@v3
      - run: echo Build
