name: CI
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  create:
    runs-on: ubuntu-latest
    steps:
      - name: created
        run: " [[ '${{ github.event.created }}' == 'false' ]] || exit 0;"
      - run: echo ${{ toJson(steps.created) }}
  build-backend:
    runs-on: ubuntu-latest
    needs: create
    steps:
      - run: echo Build backend
  build-frontend:
    runs-on: ubuntu-latest
    needs: create
    strategy:
      matrix:
        include:
          - project: peugeot
          - project: peugeot_dealer
          - project: peugeot_finance
    steps:
      - run: echo Build ${{ matrix.project }}
  e2e-test:
    runs-on: ubuntu-latest
    needs: [build-backend, build-frontend]
    steps:
      - run: echo Build ${{ matrix.project }}
  deploy-backend:
    runs-on: ubuntu-latest
    needs: [e2e-test, build-backend]
    steps:
      - run: echo Deploy backend
