name: CI
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  create:
    runs-on: ubuntu-lasest
    if: github.event.created
    steps:
      - uses: actions/checkout@v3
      - run: echo Created!
  build:
    runs-on: ubuntu-latest
    needs: create
    if: ${{ always() }}
    steps:
      - uses: actions/checkout@v3
      - run: echo ${{ needs.create.result }}
