name: CI
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  build-backend:
    runs-on: ubuntu-latest
    steps:
      - run: echo Build backend
  build-frontend:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - project: peugeot
          - project: peugeot_dealer
          - project: peugeot_finance
    steps:
      - run: echo Build ${{ matrix.project }}
  e2e-test:
    runs-on: ubuntu-latest
    needs: [build-backend, build-frontend]
    steps:
      - run: echo Build ${{ matrix.project }}
  init-backend:
    runs-on: ubuntu-latest
    needs: [e2e-test, build-backend]
    steps:
      - run: |
          if [[ '${{ github.event.created }}' == 'true' ]]; then
            echo "Create database"
          fi
  deploy-backend:
    runs-on: ubuntu-latest
    needs: [init-backend, e2e-test, build-backend]
    steps:
      - run: echo Deploy backend
