name: CI
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  create:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo ${{ github.event.created }}
  build:
    runs-on: ubuntu-latest
    needs: create
    if: ${{ always() }}
    steps:
      - uses: actions/checkout@v3
      - run: echo Hello, world!
